# Generated by Django 5.1.3 on 2024-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfile',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
