# Generated by Django 5.2.4 on 2025-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tester", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilegenerationtask",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIALIZING", "Initializing generation"),
                    ("GENERATING_CONVERSATIONS", "Generating conversations"),
                    ("CREATING_PROFILES", "Creating profiles"),
                    ("SAVING_FILES", "Saving generated files"),
                ],
                max_length=100,
            ),
        ),
    ]
