# Generated by Django 5.2.4 on 2025-07-21 18:47

import tester.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_alter_profilegenerationtask_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=tester.models.upload_to_personalities),
        ),
        migrations.AlterField(
            model_name='personalityfile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rulefile',
            name='file',
            field=models.FileField(max_length=500, upload_to=tester.models.upload_to_rules),
        ),
        migrations.AlterField(
            model_name='rulefile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=tester.models.upload_to_execution),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='typefile',
            name='file',
            field=models.FileField(max_length=500, upload_to=tester.models.upload_to_types),
        ),
        migrations.AlterField(
            model_name='typefile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
