# Generated by Django 5.2.4 on 2025-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_alter_personalityfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconnector',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Connector-specific parameters as JSON'),
        ),
        migrations.AlterField(
            model_name='chatbotconnector',
            name='link',
            field=models.URLField(blank=True, help_text='Legacy URL field - use parameters instead', null=True),
        ),
        migrations.AlterField(
            model_name='chatbotconnector',
            name='technology',
            field=models.CharField(max_length=255),
        ),
    ]
