# Generated by Django 5.2.4 on 2025-07-31 15:51

import tester.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_add_connector_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotconnector',
            name='link',
        ),
        migrations.AddField(
            model_name='chatbotconnector',
            name='custom_config_file',
            field=models.FileField(blank=True, help_text='YAML configuration file for custom connectors', null=True, upload_to=tester.models.upload_to_custom_connectors),
        ),
    ]
