# Generated by Django 5.2.4 on 2025-09-12 13:15

import django.db.models.deletion
import tester.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_remove_chatbotconnector_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenseiCheckRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=tester.models.upload_to_sensei_check_rules)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensei_check_rules', to='tester.project')),
            ],
        ),
    ]
