name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend-lint:
    name: Backend Linting & Type Checking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        working-directory: backend
        run: |
          uv sync --dev

      - name: Run ruff linting
        working-directory: backend
        run: uv run ruff check .

      - name: Run ruff formatting check
        working-directory: backend
        run: uv run ruff format --check .

      - name: Run type checking with mypy
        working-directory: backend
        run: uv run mypy . --ignore-missing-imports --no-strict-optional

  frontend-lint:
    name: Frontend Linting & Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        working-directory: frontend
        run: pnpm run lint

      - name: Check Prettier formatting
        working-directory: frontend
        run: pnpm run format:check

      - name: Build check
        working-directory: frontend
        run: pnpm run build
